### ISSUE TITLE
Duplicate documentation for snet-daemon configuration keys

### ISSUE THREAD

**Issue by ferrouswheel** [singnet/wiki#32]
Our documentation for the config of the daemon is spread all over the place. Three different repos, each covering a different set of keys.

- [example-service](https://github.com/singnet/example-service#singularitynet-daemon-configuration)
- [logger](https://github.com/singnet/snet-daemon/blob/master/logger/README.md)
- [platform-howto](https://github.com/singnet/wiki/blob/master/doc/archive/alpha/Platform-How-Tos.md#configure-singularitynet-daemon)

There should be one document describing all the keys.

I think it is fine for the detailed logger configuration to be in a separate document, but it should be linked to from the main config documentation, and be in the same repo.

I'm not sure if the canonical document should be here in the wiki repo or in the snet-daemon repo, but I'm thinking it should probably be the latter.

**Comment by vsbogd** [comment]
I would suggest keeping this documentation in [daemon-repo](https://github.com/singnet/snet-daemon/blob/master/README.md) because it is better to have it near the code.

I also agree that detailed configuration description should be removed from [platform-howto](https://github.com/singnet/wiki/blob/master/doc/archive/alpha/Platform-How-Tos.md) and [example-service](https://github.com/singnet/example-service#singularitynet-daemon-configuration). Brief description of the values one need to change to make things work should be enough for them. Both example-service and platform-howto should contain link to the daemon-repo to make it possible getting details if it is needed.

Raised issue https://github.com/singnet/snet-daemon/issues/151 to fix it in daemon.

**Comment by ferrouswheel** [comment]
Looks like all the linked PRs resolve this issue. Thanks @vsbogd!
